### ISSUE TITLE
Implementar Funções de Reserva no WebService Java

### ISSUE THREAD

**Issue by valion-lockhart** [DennyHappy/sisbb#37]
Função cadastrar();
Função atualizar();
Função getReservas($where = null);
Função getReserva($id);
Função getReserva_2($data,$hora);

**Comment by valion-lockheart** [comment]
Função cadastrar implementada.

**Comment by valion-lockheart** [comment]
Mudança de Java com SOAP para utilização de Spring com Rest

**Comment by valion-lockheart** [comment]
Função de Listagem de Reservas implementada.

Retorna:
	private Long codigo;
	private TipoReserva tipoReserva;
	private LocalDate dataReserva;
	private LocalTime horaReserva;
	private Long matricula;
	private String nomeUsuario;
	private Long codigoAgenda;
	private List<Long> codBarras = new ArrayList<Long>();
	private List<String> titulos = new ArrayList<String>();

**Comment by valion-lockheart** [comment]
Função de Cadastro de Reservas implementada.

Espera:
@NotNull
	private TipoReserva tipoReserva;
	@NotNull
	private LocalDate dataReserva;
	@NotNull
	private LocalTime horaReserva;
	@NotNull
	private Long matricula;
	@NotNull
	private Long codigoAgenda;
	@NotNull
	private List<Long> codBarras;

Retorna Os Detalhes:
private Long codigo;
private TipoReserva tipoReserva;
private LocalDate dataReserva;
private LocalTime horaReserva;
private Long matricula;
private String nomeUsuario;
private Long codigoAgenda;
private List codBarras = new ArrayList();
private List titulos = new ArrayList();

**Comment by valion-lockheart** [comment]
Funções basicas implementadas, caso seja necessário mais alguma, a tarefa será reaberta.
