### ISSUE TITLE
Implementar Funções do Livro

### ISSUE THREAD

**Issue by valion-lockhart** [DennyHappy/sisbb#41]
public function atualizar()
public function atualizar_situacao()
public static function getLivros($where = null, $join = null, $and = null, $like = null)
public static function getLivro($id)

**Comment by valion-lockheart** [comment]
Função de Listar Livros implementada.

Retorna:
private String titulo;
	private String autor;
	private String edicao;
	private String ano;
	private String volume;
	private SituacaoLivro situacao;

**Comment by valion-lockheart** [comment]
Função de Cadastrar Livros implementada.

Espera:
@NotNull
	private Long codBarras;
	private Long patrimonio;
	private String localizacao;
	@NotNull @NotEmpty @Length(min = 5)
	private String titulo;
	@NotNull @NotEmpty @Length(min = 5)
	private String autor;
	private String edicao;
	private String ano;
	private String volume;
	private SituacaoLivro situacao;
	private LocalDate dataQuarentena;

Retorna:
private String titulo;
	private String autor;
	private String edicao;
	private String ano;
	private String volume;
	private SituacaoLivro situacao;

**Comment by valion-lockheart** [comment]
Funções basicas implementadas, caso seja necessário mais alguma, a tarefa será reaberta.
