### ISSUE TITLE
Implementar Funções da Agenda

### ISSUE THREAD

**Issue by valion-lockhart** [DennyHappy/sisbb#42]
public function cadastrar()
public function atualizar()
public function excluir()
public static function getAgendas($where = null)
public static function getAgenda($id)

**Comment by valion-lockheart** [comment]
Função de Listagem de Agendas implementada.

Retorna:
private Long codigo;
private LocalDate data;
private LocalTime horaIni;
private LocalTime horaFin;

**Comment by valion-lockheart** [comment]
Função de Cadastro de Reservas implementada.

Espera:
@NotNull
private TipoReserva tipoReserva;
@NotNull
private LocalDate data;
@NotNull
private LocalTime horaIni;
@NotNull
private LocalTime horaFin;

Retorna Os Detalhes:
private Long codigo;
private LocalDate data;
private LocalTime horaIni;
private LocalTime horaFin;

**Comment by valion-lockheart** [comment]
Funções basicas implementadas, caso seja necessário mais alguma, a tarefa será reaberta.
