### ISSUE TITLE
Implementar Funções de Usuario Comum

### ISSUE THREAD

**Issue by valion-lockhart** [DennyHappy/sisbb#43]
public function cadastrar()
public static function getUsuario($email)

**Comment by valion-lockheart** [comment]
Função de Listagem de Usuários Comuns implementada.

Retorna:
private Long matricula;
private String nome;
private String email;
private String idUser;

**Comment by valion-lockheart** [comment]
Função de Cadastro de Usuários Comuns implementada.

Espera:
@NotNull
	private Long matricula;
	@NotNull @NotEmpty
	private String nome;
	@NotNull @NotEmpty
	private String email;
	@NotNull @NotEmpty
	private String idUser;

Retorna:
private Long matricula;
private String nome;
private String email;
private String idUser;

**Comment by valion-lockheart** [comment]
Funções basicas implementadas, caso seja necessário mais alguma, a tarefa será reaberta.
