### ISSUE TITLE
Implementar Funções de Usuário Bibliotecário

### ISSUE THREAD

**Issue by valion-lockhart** [DennyHappy/sisbb#44]
public function cadastrar()
public static function getUsuario($email)

**Comment by valion-lockheart** [comment]
Função de Listagem de Usuários Bibliotecários implementada.

Retorna:
private Long matricula;
private String nome;
private String email;
private String senha (temporário);

**Comment by valion-lockheart** [comment]
Função de Listagem de Usuários Bibliotecários implementada.

Espera:
private Long matricula;
private String nome;
private String email;
private String senha;

Retorna:
private Long matricula;
private String nome;
private String email;
private String senha (temporário);

**Comment by valion-lockheart** [comment]
Funções basicas implementadas, caso seja necessário mais alguma, a tarefa será reaberta.
